version: '{appveyor_repo_commit}-{build}'
image: Visual Studio 2017

build:
  verbosity: minimal
  
before_build:
  - nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '${appveyor_repo_tag_name}'
  package_version: '${appveyor_repo_tag_name}'
  assembly_version: '${appveyor_repo_tag_name}'
  file_version: '${appveyor_repo_tag_name}'
  informational_version: '${appveyor_repo_tag_name}'

deploy:
  - provider: NuGet
    api_key:
      secure: LCNNDlIjg3mq6MP2J5kE1SGK5+QRMkCBtTb3H1cy27FTEm/3KthFldRvZrAHzkGN
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    release: ${appveyor_repo_tag_name}
    description: 'Version ${appveyor_repo_tag_name}'
    auth_token:
      secure: NFu7VATIRtpS96dnh27gq3AgyBTDfD/RvLNcdgG5N0HKXYUjHZoEIMoMaFjMD6Za
    artifact: /.*Diese[^\/\\]*\.dll/
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true
